[tool.poetry]
name = "onmyoji-python"
version = "1.7.1"
description = "auto for Onmyoji"
authors = ["AquamarineCyan <1057424730@qq.com>"]
readme = "README.md"
repository = "https://github.com/AquamarineCyan/Onmyoji_Python"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pyautogui = "^0.9.53"
httpx = "^0.23.0"
pywin32 = "^305"
pyside6 = "6.3.0"
opencv-python = {extras = ["numpy"], version = "^4.7.0.72"}
pillow = "^9.4.0"
pyinstaller = "5.6.2"
pyyaml = "^6.0"
win11toast = "^0.32"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
