[tool.poetry]
name = "onmyoji-python"
version = "1.7.4"
description = "auto for Onmyoji"
authors = ["AquamarineCyan <1057424730@qq.com>"]
readme = "README.md"
repository = "https://github.com/AquamarineCyan/Onmyoji_Python"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pyautogui = "^0.9.54"
httpx = "^0.24.1"
pywin32 = "^306"
pyside6 = "^6.5.1.1"
opencv-python = "^4.7.0.72"
numpy = "^1.24.3"
pillow = "^9.5.0"
pyinstaller = "^5.12.0"
pyyaml = "^6.0"
win11toast = "^0.32"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pytest = "^7.3.2"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
