name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]
      fail-fast: false
      
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      EXE_NAME: Onmyoji_Python

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build
        run: |
            poetry run pyinstaller main.spec --clean --noconfirm --distpath .
            cd output
            dir
            # ren output.exe Onmyoji_Python.exe
      
      - name: Upload build
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{ env.EXE_NAME }}
          path: |
            output
            # ${{ env.EXE_NAME }}.exe
            # lib/
