name: Build

on:
  workflow_dispatch:
  push:
      branches:
      - dev-build

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [windows-latest]
      fail-fast: false
      
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build
        run: |
          poetry run pyinstaller main.spec
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Onmyoji_Python.exe
          path: dist/Onmyoji_Python.exe
          
