name: Test Coverage

on:
  push

jobs:
  test:
    name: Test Coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [windows-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
      - run: poetry --version
      
#      - uses: actions/checkout@v3
      
#      - name: Install poetry  
#        run: pipx install poetry
        #shell: bash
      
#      - name: Setup Python environment
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#          cache: "poetry"
        
#      - name: Install pyproject.toml
#        run: poetry install

#      - name: Run main.py
#        run: poetry run python main.py
