name: Test Coverage

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [windows-latest]
      # fail-fast: false
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.3.2"
      - run: poetry --version
      
      - name: Install dependencies
        run: poetry install
        shell: bash
      
      - name: Run Pytest
        run: |
          cd tests
          poetry run pytest -s
